"""removed student assessment table

Revision ID: 8fe3a93fa276
Revises: 69ec8ee53f0a
Create Date: 2023-11-08 20:20:08.320899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe3a93fa276'
down_revision = '69ec8ee53f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_student_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_student_association',
    sa.Column('assessment_id', sa.INTEGER(), nullable=True),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.assessment_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], )
    )
    # ### end Alembic commands ###
